# Site wide configuration

title: All Your Figure Are Belong To Us
description: "example() figures"
locale:
url: https://yutannihilation.github.io
baseurl: /allYourFigureAreBelongToUs

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
highlighter: pygments
#markdown: redcarpet
kramdown:
  toc_levels: 1..2
gems:
  - jekyll-sitemap

# Site owner
owner:
  name: Hiroaki Yutani
  email:
  twitter: yutannihilation
  bio: https://github.com/yutannihilation
excerpt_separator: ""

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
